app.url: https://orgarif.mlorber.net
logging.config: classpath:logback-prod.xml
#---------------------------------------------------------------------------
database:
  host: mut-p-pgr1.iledefrance.fr
  port: 5432
  name: orgarif
  user: orgarif
  password: sdv
spring:
  datasource:
    tomcat:
      initialSize: 5
      minIdle: 5
      maxIdle: 10
      maxActive: 10
server.forward-headers-strategy: framework
#---------------------------------------------------------------------------
assets:
  useBuildFiles: true
  browserWebpackDevHost:
  serverWebpackDevHost:
#---------------------------------------------------------------------------
mailjet:
  api-key:
  secret-key:
#---------------------------------------------------------------------------
injectFakeData: false
doSynchronizeElus: true
elusSynchronizationUrl: https://siger.mlorber.net/api/publicdata/v2/elus
