app.url: https://orgarif.iledefrance.fr
#---------------------------------------------------------------------------
database:
  host: ${ORGARIF_POSTGRESQL_HOST}
  port: ${ORGARIF_POSTGRESQL_PORT}
  name: ${ORGARIF_POSTGRESQL_DB}
  user: ${ORGARIF_POSTGRESQL_USER}
  password: ${ORGARIF_POSTGRESQL_PASSWORD}
  protocol: jdbc:postgresql
server.forward-headers-strategy: framework
#---------------------------------------------------------------------------
assets:
  useBuildFiles: true
  webpackDevPort:
  webpackDevHost:
#---------------------------------------------------------------------------
mailjet:
  apiKey:
  secretKey:
#---------------------------------------------------------------------------
sigerUrl: https://siger.iledefrance.fr
#---------------------------------------------------------------------------
