source env.sh
source secrets.sh
PGPASSWORD=$ORGARIF_POSTGRESQL_PASSWORD psql -h $ORGARIF_POSTGRESQL_HOST -p $ORGARIF_POSTGRESQL_PORT -U $ORGARIF_POSTGRESQL_USER -d $ORGARIF_POSTGRESQL_DB < initiate-database.sql